name: itsurgent
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_contacts: ^1.1.7+1
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  pinput: ^3.0.1
  cloud_firestore: ^4.15.4
  

dev_dependencies: 
  flutter_lints: 3.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

